target = 'future_close_encoded'

dict_for_features = {'GBP_USD': ['Currency',
  'Forecast',
  'Actual',
  'News_Average Hourly Earnings (MoM)',
  'News_CB Consumer Confidence',
  'News_CPI (MoM)',
  'News_CPI (YoY)',
  'News_Chicago PMI',
  'News_Core CPI (MoM)',
  'News_Core PCE Price Index (MoM)',
  'News_Core PCE Price Index (YoY)',
  'News_Core Retail Sales (MoM)',
  'News_Crude Oil Inventories',
  'News_Durable Goods Orders (MoM)',
  'News_Existing Home Sales',
  'News_Fed Interest Rate Decision',
  'News_GDP (MoM)',
  'News_GDP (QoQ)',
  'News_GDP (QoQ)  (Q1)',
  'News_GDP (QoQ)  (Q2)',
  'News_GDP (QoQ)  (Q3)',
  'News_GDP (QoQ)  (Q4)',
  'News_GDP (YoY)',						
  'News_GDP (YoY)  (Q2)',
  'News_GDP (YoY)  (Q3)',
  'News_GDP (YoY)  (Q4)',
  'News_ISM Manufacturing PMI',
  'News_ISM Manufacturing Prices',
  'News_ISM Non-Manufacturing PMI',
  'News_ISM Non-Manufacturing Prices',
  'News_Initial Jobless Claims',
  'News_JOLTS Job Openings',
  'News_New Home Sales',
  'News_Nonfarm Payrolls',
  'News_PPI (MoM)',
  'News_Philadelphia Fed Manufacturing Index',
  'News_Retail Sales (MoM)',
  'News_S&P Global Manufacturing PMI',
  'News_S&P Global Services PMI',
  'News_Unemployment Rate',
  'long_ma_cro',
  'short_ma_diff',
  'short_ma_slope',
  'long_ma_diff',
  'long_ma_slope',
  'ma_diff',
  'price_above_short_ma',
  'price_above_long_ma',
  'crossover_long_or_short',
  'EMA_50',
  'EMA_50_slope',
  'AD_EMA',
  'AD_EMA_slope',
  'RSI',
  'ATR',
  'fast_ma',
  'short_ma',
  '200_ma',
  'long_condition',
  'short_condition',
  'Change_AD',
  'Change_EMA',
  'close_above_EMA',
  'BB_MA',
  'BB_UP',
  'BB_LW',
  'BB_binary',
  'ATR_14',
  'EMA',
  'KeUp',
  'KeLo',
  'MACD',
  'SIGNAL_MACD',
  'HIST',
  'ROC',
  '+DI',
  '-DI',
  'ADX_14',
  'VWMA_14',
  'smoothed_rsi',
  'dosc',
  'derivative_oscillator',
  'Williams_R',
  'Williams_encoded',
  'Conversion_Line',
  'Base_Line',
  'Leading_Span_A',
  'Leading_Span_B',
  'Lagging_Span',
  'TSI',
  'TSI_Binary',
  'body_size_prev',
  'direction_prev',
  'direction_prev_2',
  'HANGING_MAN',
  'SHOOTING_STAR',
  'SPINNING_TOP',
  'MARUBOZU',
  'ENGULFING',
  'TWEEZER_TOP',
  'TWEEZER_BOTTOM',
  'MORNING_STAR',
  'EVENING_STAR',
  'THREE_BLACK_CROWS',
  'THREE_WHITE_SOLDIERS'],
 'USD_JPY': ['Currency',
  'Forecast',
  'Actual',
  'News_Average Hourly Earnings (MoM)',
  'News_BoJ Interest Rate Decision',
  'News_CB Consumer Confidence',
  'News_CPI (MoM)',
  'News_CPI (YoY)',
  'News_Chicago PMI',
  'News_Core CPI (MoM)',
  'News_Core PCE Price Index (MoM)',
  'News_Core PCE Price Index (YoY)',
  'News_Core Retail Sales (MoM)',
  'News_Crude Oil Inventories',
  'News_Durable Goods Orders (MoM)',
  'News_Existing Home Sales',
  'News_Fed Interest Rate Decision',
  'News_GDP (QoQ)  (Q1)',
  'News_GDP (QoQ)  (Q2)',
  'News_GDP (QoQ)  (Q3)',
  'News_GDP (QoQ)  (Q4)',
  'News_ISM Manufacturing PMI',
  'News_ISM Manufacturing Prices',
  'News_ISM Non-Manufacturing PMI',
  'News_ISM Non-Manufacturing Prices',
  'News_Initial Jobless Claims',
  'News_JOLTS Job Openings',
  'News_New Home Sales',
  'News_Nonfarm Payrolls',
  'News_PPI (MoM)',
  'News_Philadelphia Fed Manufacturing Index',
  'News_Retail Sales (MoM)',
  'News_S&P Global Manufacturing PMI',
  'News_S&P Global Services PMI',
  'News_Unemployment Rate',
  'long_ma_cro',
  'short_ma_diff',
  'short_ma_slope',
  'long_ma_diff',
  'long_ma_slope',
  'ma_diff',
  'price_above_short_ma',
  'price_above_long_ma',
  'crossover_long_or_short',
  'EMA_50',
  'EMA_50_slope',
  'AD_EMA',
  'AD_EMA_slope',
  'RSI',
  'ATR',
  'fast_ma',
  'short_ma',
  '200_ma',
  'long_condition',
  'short_condition',
  'Change_AD',
  'Change_EMA',
  'close_above_EMA',
  'BB_MA',
  'BB_UP',
  'BB_LW',
  'BB_binary',
  'ATR_14',
  'EMA',
  'KeUp',
  'KeLo',
  'MACD',
  'SIGNAL_MACD',
  'HIST',
  'ROC',
  '+DI',
  '-DI',
  'ADX_14',
  'VWMA_14',
  'smoothed_rsi',
  'dosc',
  'derivative_oscillator',
  'Williams_R',
  'Williams_encoded',
  'Conversion_Line',
  'Base_Line',
  'Leading_Span_A',
  'Leading_Span_B',
  'Lagging_Span',
  'TSI',
  'TSI_Binary',
  'body_size_prev',
  'direction_prev',
  'direction_prev_2',
  'HANGING_MAN',
  'SHOOTING_STAR',
  'SPINNING_TOP',
  'MARUBOZU',
  'ENGULFING',
  'TWEEZER_TOP',
  'TWEEZER_BOTTOM',
  'MORNING_STAR',
  'EVENING_STAR',
  'THREE_BLACK_CROWS',
  'THREE_WHITE_SOLDIERS'],
 'AUD_USD': ['Currency',
  'Forecast',
  'Actual',
  'News_Average Hourly Earnings (MoM)',
  'News_CB Consumer Confidence',
  'News_CPI (MoM)',
  'News_CPI (YoY)',
  'News_Chicago PMI',
  'News_Core CPI (MoM)',
  'News_Core PCE Price Index (MoM)',
  'News_Core PCE Price Index (YoY)',
  'News_Core Retail Sales (MoM)',
  'News_Crude Oil Inventories',
  'News_Durable Goods Orders (MoM)',
  'News_Existing Home Sales',
  'News_Fed Interest Rate Decision',
  'News_GDP (QoQ)  (Q1)',
  'News_GDP (QoQ)  (Q2)',
  'News_GDP (QoQ)  (Q3)',
  'News_GDP (QoQ)  (Q4)',
  'News_ISM Manufacturing PMI',
  'News_ISM Manufacturing Prices',
  'News_ISM Non-Manufacturing PMI',
  'News_ISM Non-Manufacturing Prices',
  'News_Initial Jobless Claims',
  'News_JOLTS Job Openings',
  'News_New Home Sales',
  'News_Nonfarm Payrolls',
  'News_PPI (MoM)',
  'News_Philadelphia Fed Manufacturing Index',
  'News_RBA Interest Rate Decision',
  'News_Retail Sales (MoM)',
  'News_S&P Global Manufacturing PMI',
  'News_S&P Global Services PMI',
  'News_Unemployment Rate',
  'long_ma_cro',
  'short_ma_diff',
  'short_ma_slope',
  'long_ma_diff',
  'long_ma_slope',
  'ma_diff',
  'price_above_short_ma',
  'price_above_long_ma',
  'crossover_long_or_short',
  'EMA_50',
  'EMA_50_slope',
  'AD_EMA',
  'AD_EMA_slope',
  'RSI',
  'ATR',
  'fast_ma',
  'short_ma',
  '200_ma',
  'long_condition',
  'short_condition',
  'Change_AD',
  'Change_EMA',
  'close_above_EMA',
  'BB_MA',
  'BB_UP',
  'BB_LW',
  'BB_binary',
  'ATR_14',
  'EMA',
  'KeUp',
  'KeLo',
  'MACD',
  'SIGNAL_MACD',
  'HIST',
  'ROC',
  '+DI',
  '-DI',
  'ADX_14',
  'VWMA_14',
  'smoothed_rsi',
  'dosc',
  'derivative_oscillator',
  'Williams_R',
  'Williams_encoded',
  'Conversion_Line',
  'Base_Line',
  'Leading_Span_A',
  'Leading_Span_B',
  'Lagging_Span',
  'TSI',
  'TSI_Binary',
  'body_size_prev',
  'direction_prev',
  'direction_prev_2',
  'HANGING_MAN',
  'SHOOTING_STAR',
  'SPINNING_TOP',
  'MARUBOZU',
  'ENGULFING',
  'TWEEZER_TOP',
  'TWEEZER_BOTTOM',
  'MORNING_STAR',
  'EVENING_STAR',
  'THREE_BLACK_CROWS',
  'THREE_WHITE_SOLDIERS'],
 'NZD_USD': ['Currency',
  'Forecast',
  'Actual',
  'News_Average Hourly Earnings (MoM)',
  'News_CB Consumer Confidence',
  'News_CPI (MoM)',
  'News_CPI (YoY)',
  'News_Chicago PMI',
  'News_Core CPI (MoM)',
  'News_Core PCE Price Index (MoM)',
  'News_Core PCE Price Index (YoY)',
  'News_Core Retail Sales (MoM)',
  'News_Crude Oil Inventories',
  'News_Durable Goods Orders (MoM)',
  'News_Existing Home Sales',
  'News_Fed Interest Rate Decision',
  'News_GDP (QoQ)  (Q1)',
  'News_GDP (QoQ)  (Q2)',
  'News_GDP (QoQ)  (Q3)',
  'News_GDP (QoQ)  (Q4)',
  'News_ISM Manufacturing PMI',
  'News_ISM Manufacturing Prices',
  'News_ISM Non-Manufacturing PMI',
  'News_ISM Non-Manufacturing Prices',
  'News_Initial Jobless Claims',
  'News_JOLTS Job Openings',
  'News_New Home Sales',
  'News_Nonfarm Payrolls',
  'News_PPI (MoM)',
  'News_Philadelphia Fed Manufacturing Index',
  'News_RBNZ Interest Rate Decision',
  'News_Retail Sales (MoM)',
  'News_S&P Global Manufacturing PMI',
  'News_S&P Global Services PMI',
  'News_Unemployment Rate',
  'long_ma_cro',
  'short_ma_diff',
  'short_ma_slope',
  'long_ma_diff',
  'long_ma_slope',
  'ma_diff',
  'price_above_short_ma',
  'price_above_long_ma',
  'crossover_long_or_short',
  'EMA_50',
  'EMA_50_slope',
  'AD_EMA',
  'AD_EMA_slope',
  'RSI',
  'ATR',
  'fast_ma',
  'short_ma',
  '200_ma',
  'long_condition',
  'short_condition',
  'Change_AD',
  'Change_EMA',
  'close_above_EMA',
  'BB_MA',
  'BB_UP',
  'BB_LW',
  'BB_binary',
  'ATR_14',
  'EMA',
  'KeUp',
  'KeLo',
  'MACD',
  'SIGNAL_MACD',
  'HIST',
  'ROC',
  '+DI',
  '-DI',
  'ADX_14',
  'VWMA_14',
  'smoothed_rsi',
  'dosc',
  'derivative_oscillator',
  'Williams_R',
  'Williams_encoded',
  'Conversion_Line',
  'Base_Line',
  'Leading_Span_A',
  'Leading_Span_B',
  'Lagging_Span',
  'TSI',
  'TSI_Binary',
  'body_size_prev',
  'direction_prev',
  'direction_prev_2',
  'HANGING_MAN',
  'SHOOTING_STAR',
  'SPINNING_TOP',
  'MARUBOZU',
  'ENGULFING',
  'TWEEZER_TOP',
  'TWEEZER_BOTTOM',
  'MORNING_STAR',
  'EVENING_STAR',
  'THREE_BLACK_CROWS',
  'THREE_WHITE_SOLDIERS'],
 'USD_CAD': ['Currency',
  'Forecast',
  'Actual',
  'News_Average Hourly Earnings (MoM)',
  'News_BoC Interest Rate Decision',
  'News_CB Consumer Confidence',
  'News_CPI (MoM)',
  'News_CPI (YoY)',
  'News_Chicago PMI',
  'News_Core CPI (MoM)',
  'News_Core PCE Price Index (MoM)',
  'News_Core PCE Price Index (YoY)',
  'News_Core Retail Sales (MoM)',
  'News_Crude Oil Inventories',
  'News_Durable Goods Orders (MoM)',
  'News_Existing Home Sales',
  'News_Fed Interest Rate Decision',
  'News_GDP (QoQ)  (Q1)',
  'News_GDP (QoQ)  (Q2)',
  'News_GDP (QoQ)  (Q3)',
  'News_GDP (QoQ)  (Q4)',
  'News_ISM Manufacturing PMI',
  'News_ISM Manufacturing Prices',
  'News_ISM Non-Manufacturing PMI',
  'News_ISM Non-Manufacturing Prices',
  'News_Initial Jobless Claims',
  'News_JOLTS Job Openings',
  'News_New Home Sales',
  'News_Nonfarm Payrolls',
  'News_PPI (MoM)',
  'News_Philadelphia Fed Manufacturing Index',
  'News_Retail Sales (MoM)',
  'News_S&P Global Manufacturing PMI',
  'News_S&P Global Services PMI',
  'News_Unemployment Rate',
  'long_ma_cro',
  'short_ma_diff',
  'short_ma_slope',
  'long_ma_diff',
  'long_ma_slope',
  'ma_diff',
  'price_above_short_ma',
  'price_above_long_ma',
  'crossover_long_or_short',
  'EMA_50',
  'EMA_50_slope',
  'AD_EMA',
  'AD_EMA_slope',
  'RSI',
  'ATR',
  'fast_ma',
  'short_ma',
  '200_ma',
  'long_condition',
  'short_condition',
  'Change_AD',
  'Change_EMA',
  'close_above_EMA',
  'BB_MA',
  'BB_UP',
  'BB_LW',
  'BB_binary',
  'ATR_14',
  'EMA',
  'KeUp',
  'KeLo',
  'MACD',
  'SIGNAL_MACD',
  'HIST',
  'ROC',
  '+DI',
  '-DI',
  'ADX_14',
  'VWMA_14',
  'smoothed_rsi',
  'dosc',
  'derivative_oscillator',
  'Williams_R',
  'Williams_encoded',
  'Conversion_Line',
  'Base_Line',
  'Leading_Span_A',
  'Leading_Span_B',
  'Lagging_Span',
  'TSI',
  'TSI_Binary',
  'body_size_prev',
  'direction_prev',
  'direction_prev_2',
  'HANGING_MAN',
  'SHOOTING_STAR',
  'SPINNING_TOP',
  'MARUBOZU',
  'ENGULFING',
  'TWEEZER_TOP',
  'TWEEZER_BOTTOM',
  'MORNING_STAR',
  'EVENING_STAR',
  'THREE_BLACK_CROWS',
  'THREE_WHITE_SOLDIERS'],
 'USD_CHF': ['Currency',
  'Forecast',
  'Actual',
  'News_Average Hourly Earnings (MoM)',
  'News_CB Consumer Confidence',
  'News_CPI (MoM)',
  'News_CPI (YoY)',
  'News_Chicago PMI',
  'News_Core CPI (MoM)',
  'News_Core PCE Price Index (MoM)',
  'News_Core PCE Price Index (YoY)',
  'News_Core Retail Sales (MoM)',
  'News_Crude Oil Inventories',
  'News_Durable Goods Orders (MoM)',
  'News_Existing Home Sales',
  'News_Fed Interest Rate Decision',
  'News_GDP (QoQ)  (Q1)',
  'News_GDP (QoQ)  (Q2)',
  'News_GDP (QoQ)  (Q3)',
  'News_GDP (QoQ)  (Q4)',
  'News_ISM Manufacturing PMI',
  'News_ISM Manufacturing Prices',
  'News_ISM Non-Manufacturing PMI',
  'News_ISM Non-Manufacturing Prices',
  'News_Initial Jobless Claims',
  'News_JOLTS Job Openings',
  'News_New Home Sales',
  'News_Nonfarm Payrolls',
  'News_PPI (MoM)',
  'News_Philadelphia Fed Manufacturing Index',
  'News_Retail Sales (MoM)',
  'News_S&P Global Manufacturing PMI',
  'News_S&P Global Services PMI',
  'News_Unemployment Rate',
  'long_ma_cro',
  'short_ma_diff',
  'short_ma_slope',
  'long_ma_diff',
  'long_ma_slope',
  'ma_diff',
  'price_above_short_ma',
  'price_above_long_ma',
  'crossover_long_or_short',
  'EMA_50',
  'EMA_50_slope',
  'AD_EMA',
  'AD_EMA_slope',
  'RSI',
  'ATR',
  'fast_ma',
  'short_ma',
  '200_ma',
  'long_condition',
  'short_condition',
  'Change_AD',
  'Change_EMA',
  'close_above_EMA',
  'BB_MA',
  'BB_UP',
  'BB_LW',
  'BB_binary',
  'ATR_14',
  'EMA',
  'KeUp',
  'KeLo',
  'MACD',
  'SIGNAL_MACD',
  'HIST',
  'ROC',
  '+DI',
  '-DI',
  'ADX_14',
  'VWMA_14',
  'smoothed_rsi',
  'dosc',
  'derivative_oscillator',
  'Williams_R',
  'Williams_encoded',
  'Conversion_Line',
  'Base_Line',
  'Leading_Span_A',
  'Leading_Span_B',
  'Lagging_Span',
  'TSI',
  'TSI_Binary',
  'body_size_prev',
  'direction_prev',
  'direction_prev_2',
  'HANGING_MAN',
  'SHOOTING_STAR',
  'SPINNING_TOP',
  'MARUBOZU',
  'ENGULFING',
  'TWEEZER_TOP',
  'TWEEZER_BOTTOM',
  'MORNING_STAR',
  'EVENING_STAR',
  'THREE_BLACK_CROWS',
  'THREE_WHITE_SOLDIERS'],
 'EUR_USD': ['Currency',
  'Forecast',
  'Actual',
  'Previous',
  'News_Average Hourly Earnings (MoM)',
  'News_CB Consumer Confidence',
  'News_CPI (MoM)',
  'News_CPI (YoY)',
  'News_Chicago PMI',
  'News_Core CPI (MoM)',
  'News_Core PCE Price Index (MoM)',
  'News_Core PCE Price Index (YoY)',
  'News_Core Retail Sales (MoM)',
  'News_Crude Oil Inventories',
  'News_Durable Goods Orders (MoM)',
  'News_ECB Interest Rate Decision',
  'News_Existing Home Sales',
  'News_Fed Interest Rate Decision',
  'News_GDP (QoQ)  (Q1)',
  'News_GDP (QoQ)  (Q2)',
  'News_GDP (QoQ)  (Q3)',
  'News_GDP (QoQ)  (Q4)',
  'News_German CPI (MoM)',
  'News_German GDP (QoQ)  (Q2)',
  'News_German GDP (QoQ)  (Q3)',
  'News_German GDP (QoQ)  (Q4)',
  'News_ISM Manufacturing PMI',
  'News_ISM Manufacturing Prices',
  'News_ISM Non-Manufacturing PMI',
  'News_ISM Non-Manufacturing Prices',
  'News_Initial Jobless Claims',
  'News_JOLTS Job Openings',
  'News_New Home Sales',
  'News_Nonfarm Payrolls',
  'News_PPI (MoM)',
  'News_Philadelphia Fed Manufacturing Index',
  'News_Retail Sales (MoM)',
  'News_S&P Global Manufacturing PMI',
  'News_S&P Global Services PMI',
  'News_Unemployment Rate',
  'acc_dis',
  'short_ma_cro',
  'long_ma_cro',
  'short_ma_diff',
  'short_ma_slope',
  'long_ma_diff',
  'long_ma_slope',
  'ma_diff',
  'price_above_short_ma',
  'price_above_long_ma',
  'crossover_long_or_short',
  'EMA_50',
  'EMA_50_slope',
  'AD_EMA',
  'AD_EMA_slope',
  'RSI',
  'ATR',
  'fast_ma',
  'short_ma',
  '200_ma',
  'long_condition',
  'short_condition',
  'Change_AD',
  'Change_EMA',
  'close_above_EMA',
  'BB_MA',
  'BB_UP',
  'BB_LW',
  'BB_binary',
  'ATR_14',
  'EMA',
  'KeUp',
  'KeLo',
  'MACD',
  'SIGNAL_MACD',
  'HIST',
  'ROC',
  '+DI',
  '-DI',
  'ADX_14',
  'VWMA_14',
  'smoothed_rsi',
  'dosc',
  'derivative_oscillator',
  'Williams_R',
  'Williams_encoded',
  'Conversion_Line',
  'Base_Line',
  'Leading_Span_A',
  'Leading_Span_B',
  'Lagging_Span',
  'TSI',
  'TSI_Binary',
  'body_size_prev',
  'direction_prev',
  'direction_prev_2',
  'HANGING_MAN',
  'SHOOTING_STAR',
  'SPINNING_TOP',
  'MARUBOZU',
  'ENGULFING',
  'TWEEZER_TOP',
  'TWEEZER_BOTTOM',
  'MORNING_STAR',
  'EVENING_STAR',
  'THREE_BLACK_CROWS',
  'THREE_WHITE_SOLDIERS'],
 'USD_CNH': ['News_Average Hourly Earnings (MoM)',
  'News_CB Consumer Confidence',
  'News_CPI (MoM)',
  'News_CPI (YoY)',
  'News_Chicago PMI',
  'News_Core CPI (MoM)',
  'News_Core PCE Price Index (MoM)',
  'News_Core PCE Price Index (YoY)',
  'News_Core Retail Sales (MoM)',
  'News_Crude Oil Inventories',
  'News_Durable Goods Orders (MoM)',
  'News_Existing Home Sales',
  'News_Fed Interest Rate Decision',
  'News_GDP (QoQ)  (Q1)',
  'News_GDP (QoQ)  (Q2)',
  'News_GDP (QoQ)  (Q3)',
  'News_GDP (QoQ)  (Q4)',
  'News_ISM Manufacturing PMI',
  'News_ISM Manufacturing Prices',
  'News_ISM Non-Manufacturing PMI',
  'News_ISM Non-Manufacturing Prices',
  'News_Initial Jobless Claims',
  'News_JOLTS Job Openings',
  'News_New Home Sales',
  'News_Nonfarm Payrolls',
  'News_PPI (MoM)',
  'News_Philadelphia Fed Manufacturing Index',
  'News_Retail Sales (MoM)',
  'News_S&P Global Manufacturing PMI',
  'News_S&P Global Services PMI',
  'News_Unemployment Rate',
  
  'Currency',
  'Forecast',
  'Actual',
  'Previous',
  'acc_dis',
  'short_ma_cro',
  'long_ma_cro',
  'short_ma_diff',
  'short_ma_slope',
  'long_ma_diff',
  'long_ma_slope',
  'ma_diff',
  'price_above_short_ma',
  'price_above_long_ma',
  'crossover_long_or_short',
  'EMA_50',
  'EMA_50_slope',
  'AD_EMA',
  'AD_EMA_slope',
  'RSI',
  'ATR',
  'fast_ma',
  'short_ma',
  '200_ma',
  'long_condition',
  'short_condition',
  'Change_AD',
  'Change_EMA',
  'close_above_EMA',
  'BB_MA',
  'BB_UP',
  'BB_LW',
  'BB_binary',
  'ATR_14',
  'EMA',
  'KeUp',
  'KeLo',
  'MACD',
  'SIGNAL_MACD',
  'HIST',
  'ROC',
  '+DI',
  '-DI',
  'ADX_14',
  'VWMA_14',
  'smoothed_rsi',
  'dosc',
  'derivative_oscillator',
  'Williams_R',
  'Williams_encoded',
  'Conversion_Line',
  'Base_Line',
  'Leading_Span_A',
  'Leading_Span_B',
  'Lagging_Span',
  'TSI',
  'TSI_Binary',
  'body_size_prev',
  'direction_prev',
  'direction_prev_2',
  'HANGING_MAN',
  'SHOOTING_STAR',
  'SPINNING_TOP',
  'MARUBOZU',
  'ENGULFING',
  'TWEEZER_TOP',
  'TWEEZER_BOTTOM',
  'MORNING_STAR',
  'EVENING_STAR',
  'THREE_BLACK_CROWS',
  'THREE_WHITE_SOLDIERS'],
 'USD_CZK': ['News_Average Hourly Earnings (MoM)',
  'News_CB Consumer Confidence',
  'News_CPI (MoM)',
  'News_CPI (YoY)',
  'News_Chicago PMI',
  'News_Core CPI (MoM)',
  'News_Core PCE Price Index (MoM)',
  'News_Core PCE Price Index (YoY)',
  'News_Core Retail Sales (MoM)',
  'News_Crude Oil Inventories',
  'News_Durable Goods Orders (MoM)',
  'News_Existing Home Sales',
  'News_Fed Interest Rate Decision',
  'News_GDP (QoQ)  (Q1)',
  'News_GDP (QoQ)  (Q2)',
  'News_GDP (QoQ)  (Q3)',
  'News_GDP (QoQ)  (Q4)',
  'News_ISM Manufacturing PMI',
  'News_ISM Manufacturing Prices',
  'News_ISM Non-Manufacturing PMI',
  'News_ISM Non-Manufacturing Prices',
  'News_Initial Jobless Claims',
  'News_JOLTS Job Openings',
  'News_New Home Sales',
  'News_Nonfarm Payrolls',
  'News_PPI (MoM)',
  'News_Philadelphia Fed Manufacturing Index',
  'News_Retail Sales (MoM)',
  'News_S&P Global Manufacturing PMI',
  'News_S&P Global Services PMI',
  'News_Unemployment Rate',
  
  'Currency',
  'Forecast',
  'Actual',
  'Previous',
  'acc_dis',
  'short_ma_cro',
  'long_ma_cro',
  'short_ma_diff',
  'short_ma_slope',
  'long_ma_diff',
  'long_ma_slope',
  'ma_diff',
  'price_above_short_ma',
  'price_above_long_ma',
  'crossover_long_or_short',
  'EMA_50',
  'EMA_50_slope',
  'AD_EMA',
  'AD_EMA_slope',
  'RSI',
  'ATR',
  'fast_ma',
  'short_ma',
  '200_ma',
  'long_condition',
  'short_condition',
  'Change_AD',
  'Change_EMA',
  'close_above_EMA',
  'BB_MA',
  'BB_UP',
  'BB_LW',
  'BB_binary',
  'ATR_14',
  'EMA',
  'KeUp',
  'KeLo',
  'MACD',
  'SIGNAL_MACD',
  'HIST',
  'ROC',
  '+DI',
  '-DI',
  'ADX_14',
  'VWMA_14',
  'smoothed_rsi',
  'dosc',
  'derivative_oscillator',
  'Williams_R',
  'Williams_encoded',
  'Conversion_Line',
  'Base_Line',
  'Leading_Span_A',
  'Leading_Span_B',
  'Lagging_Span',
  'TSI',
  'TSI_Binary',
  'body_size_prev',
  'direction_prev',
  'direction_prev_2',
  'HANGING_MAN',
  'SHOOTING_STAR',
  'SPINNING_TOP',
  'MARUBOZU',
  'ENGULFING',
  'TWEEZER_TOP',
  'TWEEZER_BOTTOM',
  'MORNING_STAR',
  'EVENING_STAR',
  'THREE_BLACK_CROWS',
  'THREE_WHITE_SOLDIERS'],
 'USD_DKK': ['News_Average Hourly Earnings (MoM)',
  'News_CB Consumer Confidence',
  'News_CPI (MoM)',
  'News_CPI (YoY)',
  'News_Chicago PMI',
  'News_Core CPI (MoM)',
  'News_Core PCE Price Index (MoM)',
  'News_Core PCE Price Index (YoY)',
  'News_Core Retail Sales (MoM)',
  'News_Crude Oil Inventories',
  'News_Durable Goods Orders (MoM)',
  'News_Existing Home Sales',
  'News_Fed Interest Rate Decision',
  'News_GDP (QoQ)  (Q1)',
  'News_GDP (QoQ)  (Q2)',
  'News_GDP (QoQ)  (Q3)',
  'News_GDP (QoQ)  (Q4)',
  'News_ISM Manufacturing PMI',
  'News_ISM Manufacturing Prices',
  'News_ISM Non-Manufacturing PMI',
  'News_ISM Non-Manufacturing Prices',
  'News_Initial Jobless Claims',
  'News_JOLTS Job Openings',
  'News_New Home Sales',
  'News_Nonfarm Payrolls',
  'News_PPI (MoM)',
  'News_Philadelphia Fed Manufacturing Index',
  'News_Retail Sales (MoM)',
  'News_S&P Global Manufacturing PMI',
  'News_S&P Global Services PMI',
  'News_Unemployment Rate',
  
  'Currency',
  'Forecast',
  'Actual',
  'Previous',
  'acc_dis',
  'short_ma_cro',
  'long_ma_cro',
  'short_ma_diff',
  'short_ma_slope',
  'long_ma_diff',
  'long_ma_slope',
  'ma_diff',
  'price_above_short_ma',
  'price_above_long_ma',
  'crossover_long_or_short',
  'EMA_50',
  'EMA_50_slope',
  'AD_EMA',
  'AD_EMA_slope',
  'RSI',
  'ATR',
  'fast_ma',
  'short_ma',
  '200_ma',
  'long_condition',
  'short_condition',
  'Change_AD',
  'Change_EMA',
  'close_above_EMA',
  'BB_MA',
  'BB_UP',
  'BB_LW',
  'BB_binary',
  'ATR_14',
  'EMA',
  'KeUp',
  'KeLo',
  'MACD',
  'SIGNAL_MACD',
  'HIST',
  'ROC',
  '+DI',
  '-DI',
  'ADX_14',
  'VWMA_14',
  'smoothed_rsi',
  'dosc',
  'derivative_oscillator',
  'Williams_R',
  'Williams_encoded',
  'Conversion_Line',
  'Base_Line',
  'Leading_Span_A',
  'Leading_Span_B',
  'Lagging_Span',
  'TSI',
  'TSI_Binary',
  'body_size_prev',
  'direction_prev',
  'direction_prev_2',
  'HANGING_MAN',
  'SHOOTING_STAR',
  'SPINNING_TOP',
  'MARUBOZU',
  'ENGULFING',
  'TWEEZER_TOP',
  'TWEEZER_BOTTOM',
  'MORNING_STAR',
  'EVENING_STAR',
  'THREE_BLACK_CROWS',
  'THREE_WHITE_SOLDIERS'],
 'USD_HKD': ['News_Average Hourly Earnings (MoM)',
  'News_CB Consumer Confidence',
  'News_CPI (MoM)',
  'News_CPI (YoY)',
  'News_Chicago PMI',
  'News_Core CPI (MoM)',
  'News_Core PCE Price Index (MoM)',
  'News_Core PCE Price Index (YoY)',
  'News_Core Retail Sales (MoM)',
  'News_Crude Oil Inventories',
  'News_Durable Goods Orders (MoM)',
  'News_Existing Home Sales',
  'News_Fed Interest Rate Decision',
  'News_GDP (QoQ)  (Q1)',
  'News_GDP (QoQ)  (Q2)',
  'News_GDP (QoQ)  (Q3)',
  'News_GDP (QoQ)  (Q4)',
  'News_ISM Manufacturing PMI',
  'News_ISM Manufacturing Prices',
  'News_ISM Non-Manufacturing PMI',
  'News_ISM Non-Manufacturing Prices',
  'News_Initial Jobless Claims',
  'News_JOLTS Job Openings',
  'News_New Home Sales',
  'News_Nonfarm Payrolls',
  'News_PPI (MoM)',
  'News_Philadelphia Fed Manufacturing Index',
  'News_Retail Sales (MoM)',
  'News_S&P Global Manufacturing PMI',
  'News_S&P Global Services PMI',
  'News_Unemployment Rate',
  
  'Currency',
  'Forecast',
  'Actual',
  'Previous',
  'acc_dis',
  'short_ma_cro',
  'long_ma_cro',
  'short_ma_diff',
  'short_ma_slope',
  'long_ma_diff',
  'long_ma_slope',
  'ma_diff',
  'price_above_short_ma',
  'price_above_long_ma',
  'crossover_long_or_short',
  'EMA_50',
  'EMA_50_slope',
  'AD_EMA',
  'AD_EMA_slope',
  'RSI',
  'ATR',
  'fast_ma',
  'short_ma',
  '200_ma',
  'long_condition',
  'short_condition',
  'Change_AD',
  'Change_EMA',
  'close_above_EMA',
  'BB_MA',
  'BB_UP',
  'BB_LW',
  'BB_binary',
  'ATR_14',
  'EMA',
  'KeUp',
  'KeLo',
  'MACD',
  'SIGNAL_MACD',
  'HIST',
  'ROC',
  '+DI',
  '-DI',
  'ADX_14',
  'VWMA_14',
  'smoothed_rsi',
  'dosc',
  'derivative_oscillator',
  'Williams_R',
  'Williams_encoded',
  'Conversion_Line',
  'Base_Line',
  'Leading_Span_A',
  'Leading_Span_B',
  'Lagging_Span',
  'TSI',
  'TSI_Binary',
  'body_size_prev',
  'direction_prev',
  'direction_prev_2',
  'HANGING_MAN',
  'SHOOTING_STAR',
  'SPINNING_TOP',
  'MARUBOZU',
  'ENGULFING',
  'TWEEZER_TOP',
  'TWEEZER_BOTTOM',
  'MORNING_STAR',
  'EVENING_STAR',
  'THREE_BLACK_CROWS',
  'THREE_WHITE_SOLDIERS'],
 'USD_HUF': ['News_Average Hourly Earnings (MoM)',
  'News_CB Consumer Confidence',
  'News_CPI (MoM)',
  'News_CPI (YoY)',
  'News_Chicago PMI',
  'News_Core CPI (MoM)',
  'News_Core PCE Price Index (MoM)',
  'News_Core PCE Price Index (YoY)',
  'News_Core Retail Sales (MoM)',
  'News_Crude Oil Inventories',
  'News_Durable Goods Orders (MoM)',
  'News_Existing Home Sales',
  'News_Fed Interest Rate Decision',
  'News_GDP (QoQ)  (Q1)',
  'News_GDP (QoQ)  (Q2)',
  'News_GDP (QoQ)  (Q3)',
  'News_GDP (QoQ)  (Q4)',
  'News_ISM Manufacturing PMI',
  'News_ISM Manufacturing Prices',
  'News_ISM Non-Manufacturing PMI',
  'News_ISM Non-Manufacturing Prices',
  'News_Initial Jobless Claims',
  'News_JOLTS Job Openings',
  'News_New Home Sales',
  'News_Nonfarm Payrolls',
  'News_PPI (MoM)',
  'News_Philadelphia Fed Manufacturing Index',
  'News_Retail Sales (MoM)',
  'News_S&P Global Manufacturing PMI',
  'News_S&P Global Services PMI',
  'News_Unemployment Rate',
  
  'Currency',
  'Forecast',
  'Actual',
  'Previous',
  'acc_dis',
  'short_ma_cro',
  'long_ma_cro',
  'short_ma_diff',
  'short_ma_slope',
  'long_ma_diff',
  'long_ma_slope',
  'ma_diff',
  'price_above_short_ma',
  'price_above_long_ma',
  'crossover_long_or_short',
  'EMA_50',
  'EMA_50_slope',
  'AD_EMA',
  'AD_EMA_slope',
  'RSI',
  'ATR',
  'fast_ma',
  'short_ma',
  '200_ma',
  'long_condition',
  'short_condition',
  'Change_AD',
  'Change_EMA',
  'close_above_EMA',
  'BB_MA',
  'BB_UP',
  'BB_LW',
  'BB_binary',
  'ATR_14',
  'EMA',
  'KeUp',
  'KeLo',
  'MACD',
  'SIGNAL_MACD',
  'HIST',
  'ROC',
  '+DI',
  '-DI',
  'ADX_14',
  'VWMA_14',
  'smoothed_rsi',
  'dosc',
  'derivative_oscillator',
  'Williams_R',
  'Williams_encoded',
  'Conversion_Line',
  'Base_Line',
  'Leading_Span_A',
  'Leading_Span_B',
  'Lagging_Span',
  'TSI',
  'TSI_Binary',
  'body_size_prev',
  'direction_prev',
  'direction_prev_2',
  'HANGING_MAN',
  'SHOOTING_STAR',
  'SPINNING_TOP',
  'MARUBOZU',
  'ENGULFING',
  'TWEEZER_TOP',
  'TWEEZER_BOTTOM',
  'MORNING_STAR',
  'EVENING_STAR',
  'THREE_BLACK_CROWS',
  'THREE_WHITE_SOLDIERS'],
 'USD_MXN': ['News_Average Hourly Earnings (MoM)',
  'News_CB Consumer Confidence',
  'News_CPI (MoM)',
  'News_CPI (YoY)',
  'News_Chicago PMI',
  'News_Core CPI (MoM)',
  'News_Core PCE Price Index (MoM)',
  'News_Core PCE Price Index (YoY)',
  'News_Core Retail Sales (MoM)',
  'News_Crude Oil Inventories',
  'News_Durable Goods Orders (MoM)',
  'News_Existing Home Sales',
  'News_Fed Interest Rate Decision',
  'News_GDP (QoQ)  (Q1)',
  'News_GDP (QoQ)  (Q2)',
  'News_GDP (QoQ)  (Q3)',
  'News_GDP (QoQ)  (Q4)',
  'News_ISM Manufacturing PMI',
  'News_ISM Manufacturing Prices',
  'News_ISM Non-Manufacturing PMI',
  'News_ISM Non-Manufacturing Prices',
  'News_Initial Jobless Claims',
  'News_JOLTS Job Openings',
  'News_New Home Sales',
  'News_Nonfarm Payrolls',
  'News_PPI (MoM)',
  'News_Philadelphia Fed Manufacturing Index',
  'News_Retail Sales (MoM)',
  'News_S&P Global Manufacturing PMI',
  'News_S&P Global Services PMI',
  'News_Unemployment Rate',
  
  'Currency',
  'Forecast',
  'Actual',
  'Previous',
  'acc_dis',
  'short_ma_cro',
  'long_ma_cro',
  'short_ma_diff',
  'short_ma_slope',
  'long_ma_diff',
  'long_ma_slope',
  'ma_diff',
  'price_above_short_ma',
  'price_above_long_ma',
  'crossover_long_or_short',
  'EMA_50',
  'EMA_50_slope',
  'AD_EMA',
  'AD_EMA_slope',
  'RSI',
  'ATR',
  'fast_ma',
  'short_ma',
  '200_ma',
  'long_condition',
  'short_condition',
  'Change_AD',
  'Change_EMA',
  'close_above_EMA',
  'BB_MA',
  'BB_UP',
  'BB_LW',
  'BB_binary',
  'ATR_14',
  'EMA',
  'KeUp',
  'KeLo',
  'MACD',
  'SIGNAL_MACD',
  'HIST',
  'ROC',
  '+DI',
  '-DI',
  'ADX_14',
  'VWMA_14',
  'smoothed_rsi',
  'dosc',
  'derivative_oscillator',
  'Williams_R',
  'Williams_encoded',
  'Conversion_Line',
  'Base_Line',
  'Leading_Span_A',
  'Leading_Span_B',
  'Lagging_Span',
  'TSI',
  'TSI_Binary',
  'body_size_prev',
  'direction_prev',
  'direction_prev_2',
  'HANGING_MAN',
  'SHOOTING_STAR',
  'SPINNING_TOP',
  'MARUBOZU',
  'ENGULFING',
  'TWEEZER_TOP',
  'TWEEZER_BOTTOM',
  'MORNING_STAR',
  'EVENING_STAR',
  'THREE_BLACK_CROWS',
  'THREE_WHITE_SOLDIERS'],
 'USD_NOK': ['News_Average Hourly Earnings (MoM)',
  'News_CB Consumer Confidence',
  'News_CPI (MoM)',
  'News_CPI (YoY)',
  'News_Chicago PMI',
  'News_Core CPI (MoM)',
  'News_Core PCE Price Index (MoM)',
  'News_Core PCE Price Index (YoY)',
  'News_Core Retail Sales (MoM)',
  'News_Crude Oil Inventories',
  'News_Durable Goods Orders (MoM)',
  'News_Existing Home Sales',
  'News_Fed Interest Rate Decision',
  'News_GDP (QoQ)  (Q1)',
  'News_GDP (QoQ)  (Q2)',
  'News_GDP (QoQ)  (Q3)',
  'News_GDP (QoQ)  (Q4)',
  'News_ISM Manufacturing PMI',
  'News_ISM Manufacturing Prices',
  'News_ISM Non-Manufacturing PMI',
  'News_ISM Non-Manufacturing Prices',
  'News_Initial Jobless Claims',
  'News_JOLTS Job Openings',
  'News_New Home Sales',
  'News_Nonfarm Payrolls',
  'News_PPI (MoM)',
  'News_Philadelphia Fed Manufacturing Index',
  'News_Retail Sales (MoM)',
  'News_S&P Global Manufacturing PMI',
  'News_S&P Global Services PMI',
  'News_Unemployment Rate',
  
  'Currency',
  'Forecast',
  'Actual',
  'Previous',
  'acc_dis',
  'short_ma_cro',
  'long_ma_cro',
  'short_ma_diff',
  'short_ma_slope',
  'long_ma_diff',
  'long_ma_slope',
  'ma_diff',
  'price_above_short_ma',
  'price_above_long_ma',
  'crossover_long_or_short',
  'EMA_50',
  'EMA_50_slope',
  'AD_EMA',
  'AD_EMA_slope',
  'RSI',
  'ATR',
  'fast_ma',
  'short_ma',
  '200_ma',
  'long_condition',
  'short_condition',
  'Change_AD',
  'Change_EMA',
  'close_above_EMA',
  'BB_MA',
  'BB_UP',
  'BB_LW',
  'BB_binary',
  'ATR_14',
  'EMA',
  'KeUp',
  'KeLo',
  'MACD',
  'SIGNAL_MACD',
  'HIST',
  'ROC',
  '+DI',
  '-DI',
  'ADX_14',
  'VWMA_14',
  'smoothed_rsi',
  'dosc',
  'derivative_oscillator',
  'Williams_R',
  'Williams_encoded',
  'Conversion_Line',
  'Base_Line',
  'Leading_Span_A',
  'Leading_Span_B',
  'Lagging_Span',
  'TSI',
  'TSI_Binary',
  'body_size_prev',
  'direction_prev',
  'direction_prev_2',
  'HANGING_MAN',
  'SHOOTING_STAR',
  'SPINNING_TOP',
  'MARUBOZU',
  'ENGULFING',
  'TWEEZER_TOP',
  'TWEEZER_BOTTOM',
  'MORNING_STAR',
  'EVENING_STAR',
  'THREE_BLACK_CROWS',
  'THREE_WHITE_SOLDIERS'],
 'USD_PLN': ['News_Average Hourly Earnings (MoM)',
  'News_CB Consumer Confidence',
  'News_CPI (MoM)',
  'News_CPI (YoY)',
  'News_Chicago PMI',
  'News_Core CPI (MoM)',
  'News_Core PCE Price Index (MoM)',
  'News_Core PCE Price Index (YoY)',
  'News_Core Retail Sales (MoM)',
  'News_Crude Oil Inventories',
  'News_Durable Goods Orders (MoM)',
  'News_Existing Home Sales',
  'News_Fed Interest Rate Decision',
  'News_GDP (QoQ)  (Q1)',
  'News_GDP (QoQ)  (Q2)',
  'News_GDP (QoQ)  (Q3)',
  'News_GDP (QoQ)  (Q4)',
  'News_ISM Manufacturing PMI',
  'News_ISM Manufacturing Prices',
  'News_ISM Non-Manufacturing PMI',
  'News_ISM Non-Manufacturing Prices',
  'News_Initial Jobless Claims',
  'News_JOLTS Job Openings',
  'News_New Home Sales',
  'News_Nonfarm Payrolls',
  'News_PPI (MoM)',
  'News_Philadelphia Fed Manufacturing Index',
  'News_Retail Sales (MoM)',
  'News_S&P Global Manufacturing PMI',
  'News_S&P Global Services PMI',
  'News_Unemployment Rate',
  
  'Currency',
  'Forecast',
  'Actual',
  'Previous',
  'acc_dis',
  'short_ma_cro',
  'long_ma_cro',
  'short_ma_diff',
  'short_ma_slope',
  'long_ma_diff',
  'long_ma_slope',
  'ma_diff',
  'price_above_short_ma',
  'price_above_long_ma',
  'crossover_long_or_short',
  'EMA_50',
  'EMA_50_slope',
  'AD_EMA',
  'AD_EMA_slope',
  'RSI',
  'ATR',
  'fast_ma',
  'short_ma',
  '200_ma',
  'long_condition',
  'short_condition',
  'Change_AD',
  'Change_EMA',
  'close_above_EMA',
  'BB_MA',
  'BB_UP',
  'BB_LW',
  'BB_binary',
  'ATR_14',
  'EMA',
  'KeUp',
  'KeLo',
  'MACD',
  'SIGNAL_MACD',
  'HIST',
  'ROC',
  '+DI',
  '-DI',
  'ADX_14',
  'VWMA_14',
  'smoothed_rsi',
  'dosc',
  'derivative_oscillator',
  'Williams_R',
  'Williams_encoded',
  'Conversion_Line',
  'Base_Line',
  'Leading_Span_A',
  'Leading_Span_B',
  'Lagging_Span',
  'TSI',
  'TSI_Binary',
  'body_size_prev',
  'direction_prev',
  'direction_prev_2',
  'HANGING_MAN',
  'SHOOTING_STAR',
  'SPINNING_TOP',
  'MARUBOZU',
  'ENGULFING',
  'TWEEZER_TOP',
  'TWEEZER_BOTTOM',
  'MORNING_STAR',
  'EVENING_STAR',
  'THREE_BLACK_CROWS',
  'THREE_WHITE_SOLDIERS'],
 'USD_SEK': ['News_Average Hourly Earnings (MoM)',
  'News_CB Consumer Confidence',
  'News_CPI (MoM)',
  'News_CPI (YoY)',
  'News_Chicago PMI',
  'News_Core CPI (MoM)',
  'News_Core PCE Price Index (MoM)',
  'News_Core PCE Price Index (YoY)',
  'News_Core Retail Sales (MoM)',
  'News_Crude Oil Inventories',
  'News_Durable Goods Orders (MoM)',
  'News_Existing Home Sales',
  'News_Fed Interest Rate Decision',
  'News_GDP (QoQ)  (Q1)',
  'News_GDP (QoQ)  (Q2)',
  'News_GDP (QoQ)  (Q3)',
  'News_GDP (QoQ)  (Q4)',
  'News_ISM Manufacturing PMI',
  'News_ISM Manufacturing Prices',
  'News_ISM Non-Manufacturing PMI',
  'News_ISM Non-Manufacturing Prices',
  'News_Initial Jobless Claims',
  'News_JOLTS Job Openings',
  'News_New Home Sales',
  'News_Nonfarm Payrolls',
  'News_PPI (MoM)',
  'News_Philadelphia Fed Manufacturing Index',
  'News_Retail Sales (MoM)',
  'News_S&P Global Manufacturing PMI',
  'News_S&P Global Services PMI',
  'News_Unemployment Rate',
  
  'Currency',
  'Forecast',
  'Actual',
  'Previous',
  'acc_dis',
  'short_ma_cro',
  'long_ma_cro',
  'short_ma_diff',
  'short_ma_slope',
  'long_ma_diff',
  'long_ma_slope',
  'ma_diff',
  'price_above_short_ma',
  'price_above_long_ma',
  'crossover_long_or_short',
  'EMA_50',
  'EMA_50_slope',
  'AD_EMA',
  'AD_EMA_slope',
  'RSI',
  'ATR',
  'fast_ma',
  'short_ma',
  '200_ma',
  'long_condition',
  'short_condition',
  'Change_AD',
  'Change_EMA',
  'close_above_EMA',
  'BB_MA',
  'BB_UP',
  'BB_LW',
  'BB_binary',
  'ATR_14',
  'EMA',
  'KeUp',
  'KeLo',
  'MACD',
  'SIGNAL_MACD',
  'HIST',
  'ROC',
  '+DI',
  '-DI',
  'ADX_14',
  'VWMA_14',
  'smoothed_rsi',
  'dosc',
  'derivative_oscillator',
  'Williams_R',
  'Williams_encoded',
  'Conversion_Line',
  'Base_Line',
  'Leading_Span_A',
  'Leading_Span_B',
  'Lagging_Span',
  'TSI',
  'TSI_Binary',
  'body_size_prev',
  'direction_prev',
  'direction_prev_2',
  'HANGING_MAN',
  'SHOOTING_STAR',
  'SPINNING_TOP',
  'MARUBOZU',
  'ENGULFING',
  'TWEEZER_TOP',
  'TWEEZER_BOTTOM',
  'MORNING_STAR',
  'EVENING_STAR',
  'THREE_BLACK_CROWS',
  'THREE_WHITE_SOLDIERS'],
 'USD_SGD': ['News_Average Hourly Earnings (MoM)',
  'News_CB Consumer Confidence',
  'News_CPI (MoM)',
  'News_CPI (YoY)',
  'News_Chicago PMI',
  'News_Core CPI (MoM)',
  'News_Core PCE Price Index (MoM)',
  'News_Core PCE Price Index (YoY)',
  'News_Core Retail Sales (MoM)',
  'News_Crude Oil Inventories',
  'News_Durable Goods Orders (MoM)',
  'News_Existing Home Sales',
  'News_Fed Interest Rate Decision',
  'News_GDP (QoQ)  (Q1)',
  'News_GDP (QoQ)  (Q2)',
  'News_GDP (QoQ)  (Q3)',
  'News_GDP (QoQ)  (Q4)',
  'News_ISM Manufacturing PMI',
  'News_ISM Manufacturing Prices',
  'News_ISM Non-Manufacturing PMI',
  'News_ISM Non-Manufacturing Prices',
  'News_Initial Jobless Claims',
  'News_JOLTS Job Openings',
  'News_New Home Sales',
  'News_Nonfarm Payrolls',
  'News_PPI (MoM)',
  'News_Philadelphia Fed Manufacturing Index',
  'News_Retail Sales (MoM)',
  'News_S&P Global Manufacturing PMI',
  'News_S&P Global Services PMI',
  'News_Unemployment Rate',
  
  'Currency',
  'Forecast',
  'Actual',
  'Previous',
  'acc_dis',
  'short_ma_cro',
  'long_ma_cro',
  'short_ma_diff',
  'short_ma_slope',
  'long_ma_diff',
  'long_ma_slope',
  'ma_diff',
  'price_above_short_ma',
  'price_above_long_ma',
  'crossover_long_or_short',
  'EMA_50',
  'EMA_50_slope',
  'AD_EMA',
  'AD_EMA_slope',
  'RSI',
  'ATR',
  'fast_ma',
  'short_ma',
  '200_ma',
  'long_condition',
  'short_condition',
  'Change_AD',
  'Change_EMA',
  'close_above_EMA',
  'BB_MA',
  'BB_UP',
  'BB_LW',
  'BB_binary',
  'ATR_14',
  'EMA',
  'KeUp',
  'KeLo',
  'MACD',
  'SIGNAL_MACD',
  'HIST',
  'ROC',
  '+DI',
  '-DI',
  'ADX_14',
  'VWMA_14',
  'smoothed_rsi',
  'dosc',
  'derivative_oscillator',
  'Williams_R',
  'Williams_encoded',
  'Conversion_Line',
  'Base_Line',
  'Leading_Span_A',
  'Leading_Span_B',
  'Lagging_Span',
  'TSI',
  'TSI_Binary',
  'body_size_prev',
  'direction_prev',
  'direction_prev_2',
  'HANGING_MAN',
  'SHOOTING_STAR',
  'SPINNING_TOP',
  'MARUBOZU',
  'ENGULFING',
  'TWEEZER_TOP',
  'TWEEZER_BOTTOM',
  'MORNING_STAR',
  'EVENING_STAR',
  'THREE_BLACK_CROWS',
  'THREE_WHITE_SOLDIERS'],
 'USD_THB': ['News_Average Hourly Earnings (MoM)',
  'News_CB Consumer Confidence',
  'News_CPI (MoM)',
  'News_CPI (YoY)',
  'News_Chicago PMI',
  'News_Core CPI (MoM)',
  'News_Core PCE Price Index (MoM)',
  'News_Core PCE Price Index (YoY)',
  'News_Core Retail Sales (MoM)',
  'News_Crude Oil Inventories',
  'News_Durable Goods Orders (MoM)',
  'News_Existing Home Sales',
  'News_Fed Interest Rate Decision',
  'News_GDP (QoQ)  (Q1)',
  'News_GDP (QoQ)  (Q2)',
  'News_GDP (QoQ)  (Q3)',
  'News_GDP (QoQ)  (Q4)',
  'News_ISM Manufacturing PMI',
  'News_ISM Manufacturing Prices',
  'News_ISM Non-Manufacturing PMI',
  'News_ISM Non-Manufacturing Prices',
  'News_Initial Jobless Claims',
  'News_JOLTS Job Openings',
  'News_New Home Sales',
  'News_Nonfarm Payrolls',
  'News_PPI (MoM)',
  'News_Philadelphia Fed Manufacturing Index',
  'News_Retail Sales (MoM)',
  'News_S&P Global Manufacturing PMI',
  'News_S&P Global Services PMI',
  'News_Unemployment Rate',
  
  'Currency',
  'Forecast',
  'Actual',
  'Previous',
  'acc_dis',
  'short_ma_cro',
  'long_ma_cro',
  'short_ma_diff',
  'short_ma_slope',
  'long_ma_diff',
  'long_ma_slope',
  'ma_diff',
  'price_above_short_ma',
  'price_above_long_ma',
  'crossover_long_or_short',
  'EMA_50',
  'EMA_50_slope',
  'AD_EMA',
  'AD_EMA_slope',
  'RSI',
  'ATR',
  'fast_ma',
  'short_ma',
  '200_ma',
  'long_condition',
  'short_condition',
  'Change_AD',
  'Change_EMA',
  'close_above_EMA',
  'BB_MA',
  'BB_UP',
  'BB_LW',
  'BB_binary',
  'ATR_14',
  'EMA',
  'KeUp',
  'KeLo',
  'MACD',
  'SIGNAL_MACD',
  'HIST',
  'ROC',
  '+DI',
  '-DI',
  'ADX_14',
  'VWMA_14',
  'smoothed_rsi',
  'dosc',
  'derivative_oscillator',
  'Williams_R',
  'Williams_encoded',
  'Conversion_Line',
  'Base_Line',
  'Leading_Span_A',
  'Leading_Span_B',
  'Lagging_Span',
  'TSI',
  'TSI_Binary',
  'body_size_prev',
  'direction_prev',
  'direction_prev_2',
  'HANGING_MAN',
  'SHOOTING_STAR',
  'SPINNING_TOP',
  'MARUBOZU',
  'ENGULFING',
  'TWEEZER_TOP',
  'TWEEZER_BOTTOM',
  'MORNING_STAR',
  'EVENING_STAR',
  'THREE_BLACK_CROWS',
  'THREE_WHITE_SOLDIERS'],
 'USD_TRY': ['News_Average Hourly Earnings (MoM)',
  'News_CB Consumer Confidence',
  'News_CPI (MoM)',
  'News_CPI (YoY)',
  'News_Chicago PMI',
  'News_Core CPI (MoM)',
  'News_Core PCE Price Index (MoM)',
  'News_Core PCE Price Index (YoY)',
  'News_Core Retail Sales (MoM)',
  'News_Crude Oil Inventories',
  'News_Durable Goods Orders (MoM)',
  'News_Existing Home Sales',
  'News_Fed Interest Rate Decision',
  'News_GDP (QoQ)  (Q1)',
  'News_GDP (QoQ)  (Q2)',
  'News_GDP (QoQ)  (Q3)',
  'News_GDP (QoQ)  (Q4)',
  'News_ISM Manufacturing PMI',
  'News_ISM Manufacturing Prices',
  'News_ISM Non-Manufacturing PMI',
  'News_ISM Non-Manufacturing Prices',
  'News_Initial Jobless Claims',
  'News_JOLTS Job Openings',
  'News_New Home Sales',
  'News_Nonfarm Payrolls',
  'News_PPI (MoM)',
  'News_Philadelphia Fed Manufacturing Index',
  'News_Retail Sales (MoM)',
  'News_S&P Global Manufacturing PMI',
  'News_S&P Global Services PMI',
  'News_Unemployment Rate',
  
  'Currency',
  'Forecast',
  'Actual',
  'Previous',
  'acc_dis',
  'short_ma_cro',
  'long_ma_cro',
  'short_ma_diff',
  'short_ma_slope',
  'long_ma_diff',
  'long_ma_slope',
  'ma_diff',
  'price_above_short_ma',
  'price_above_long_ma',
  'crossover_long_or_short',
  'EMA_50',
  'EMA_50_slope',
  'AD_EMA',
  'AD_EMA_slope',
  'RSI',
  'ATR',
  'fast_ma',
  'short_ma',
  '200_ma',
  'long_condition',
  'short_condition',
  'Change_AD',
  'Change_EMA',
  'close_above_EMA',
  'BB_MA',
  'BB_UP',
  'BB_LW',
  'BB_binary',
  'ATR_14',
  'EMA',
  'KeUp',
  'KeLo',
  'MACD',
  'SIGNAL_MACD',
  'HIST',
  'ROC',
  '+DI',
  '-DI',
  'ADX_14',
  'VWMA_14',
  'smoothed_rsi',
  'dosc',
  'derivative_oscillator',
  'Williams_R',
  'Williams_encoded',
  'Conversion_Line',
  'Base_Line',
  'Leading_Span_A',
  'Leading_Span_B',
  'Lagging_Span',
  'TSI',
  'TSI_Binary',
  'body_size_prev',
  'direction_prev',
  'direction_prev_2',
  'HANGING_MAN',
  'SHOOTING_STAR',
  'SPINNING_TOP',
  'MARUBOZU',
  'ENGULFING',
  'TWEEZER_TOP',
  'TWEEZER_BOTTOM',
  'MORNING_STAR',
  'EVENING_STAR',
  'THREE_BLACK_CROWS',
  'THREE_WHITE_SOLDIERS'],
 'USD_ZAR': ['News_Average Hourly Earnings (MoM)',
  'News_CB Consumer Confidence',
  'News_CPI (MoM)',
  'News_CPI (YoY)',
  'News_Chicago PMI',
  'News_Core CPI (MoM)',
  'News_Core PCE Price Index (MoM)',
  'News_Core PCE Price Index (YoY)',
  'News_Core Retail Sales (MoM)',
  'News_Crude Oil Inventories',
  'News_Durable Goods Orders (MoM)',
  'News_Existing Home Sales',
  'News_Fed Interest Rate Decision',
  'News_GDP (QoQ)  (Q1)',
  'News_GDP (QoQ)  (Q2)',
  'News_GDP (QoQ)  (Q3)',
  'News_GDP (QoQ)  (Q4)',
  'News_ISM Manufacturing PMI',
  'News_ISM Manufacturing Prices',
  'News_ISM Non-Manufacturing PMI',
  'News_ISM Non-Manufacturing Prices',
  'News_Initial Jobless Claims',
  'News_JOLTS Job Openings',
  'News_New Home Sales',
  'News_Nonfarm Payrolls',
  'News_PPI (MoM)',
  'News_Philadelphia Fed Manufacturing Index',
  'News_Retail Sales (MoM)',
  'News_S&P Global Manufacturing PMI',
  'News_S&P Global Services PMI',
  'News_Unemployment Rate',
  
  'Currency',
  'Forecast',
  'Actual',
  'Previous',
  'acc_dis',
  'short_ma_cro',
  'long_ma_cro',
  'short_ma_diff',
  'short_ma_slope',
  'long_ma_diff',
  'long_ma_slope',
  'ma_diff',
  'price_above_short_ma',
  'price_above_long_ma',
  'crossover_long_or_short',
  'EMA_50',
  'EMA_50_slope',
  'AD_EMA',
  'AD_EMA_slope',
  'RSI',
  'ATR',
  'fast_ma',
  'short_ma',
  '200_ma',
  'long_condition',
  'short_condition',
  'Change_AD',
  'Change_EMA',
  'close_above_EMA',
  'BB_MA',
  'BB_UP',
  'BB_LW',
  'BB_binary',
  'ATR_14',
  'EMA',
  'KeUp',
  'KeLo',
  'MACD',
  'SIGNAL_MACD',
  'HIST',
  'ROC',
  '+DI',
  '-DI',
  'ADX_14',
  'VWMA_14',
  'smoothed_rsi',
  'dosc',
  'derivative_oscillator',
  'Williams_R',
  'Williams_encoded',
  'Conversion_Line',
  'Base_Line',
  'Leading_Span_A',
  'Leading_Span_B',
  'Lagging_Span',
  'TSI',
  'TSI_Binary',
  'body_size_prev',
  'direction_prev',
  'direction_prev_2',
  'HANGING_MAN',
  'SHOOTING_STAR',
  'SPINNING_TOP',
  'MARUBOZU',
  'ENGULFING',
  'TWEEZER_TOP',
  'TWEEZER_BOTTOM',
  'MORNING_STAR',
  'EVENING_STAR',
  'THREE_BLACK_CROWS',
  'THREE_WHITE_SOLDIERS']}